fix: 예약 및 취소 시, 로딩 추가
undefined-dev-ko/ship-check-fe pull request #30
Opened 2024-06-30 06:05 UTC by songseungeun

화면 로딩을 데스크 내 로딩으로 수정하고, 예약 및 취소 시 모두 추가했습니다..!
그리고 로딩 모션을 좀 덜 까부는 것으로 수정했어용..ㅋㅋㅋ

2024-06-30 11:52 UTC, KadyoYang approved these changes
고생하셨습니다!

2024-06-30 12:35 UTC, Jang184 requested changes
로딩 뜨는 것 확인했습니다! 고생 많으셨습니다 👍

2024-06-30 12:35 UTC, Jang184 commented on src/components/Reservation/Desk/index.tsx
> -  if (!seat) {
```
Cannot destructure property 'fixedUser' of 'seat' as it is undefined.
```
위 오류가 발생해서 seat가 없을 때 예외처리를 해주어야 할 것 같습니다 !

2024-07-01 09:14 UTC, Jang184 approved these changes

2024-07-01 09:15 UTC, merged